use project_demo;

describe customer;
describe employee;
describe orderdetails;
describe orders;
describe product;
describe region;
describe warehouse;

select * from customer;
select * from employee;
select * from orderdetails;
select * from orders;
select * from product;
select * from region;
select * from warehouse;

update employee
set employeehiredate = str_to_date(employeehiredate,'%d-%m-%Y');

alter table employee
modify employeehiredate date;

alter table orders
modify orderdate date;

-- 🟢 Basic —  

-- Q1 Display the names, email addresses, and credit limits of all customers.
select 
	customername,
    customeremail,
    customercreditlimit
from customer;

-- Q2 Find all customers whose credit limit is greater than 3000.
select *
from customer
where customercreditlimit > 3000;

-- Q3 Display the details of employees whose job title is 'Programmer' and who were hired after January 2016.
select *
from employee
where employeejobtitle ='programmer' and employeehiredate > '2016-01-31';

-- Q4 Display all products with their product name, category and list price, sorted by list price from highest to lowest.
select 
	productname,
    categoryname,
    productlistprice
from product 
order by productlistprice desc;

-- Q5 Find the 5 most expensive products based on their list price.
select * 
from product 
order by productlistprice desc
limit 5;

-- Q6 Display all unique product categories available in the product table.
select 
	distinct categoryname 
from product;

-- Q7 Find all order details where the order item quantity is greater than 100 and sort them by quantity in descending order.
select *
from orderdetails
where orderitemquantity > 100
order by orderitemquantity desc;

-- Q8 Find the 10 products with the highest profit and display their ProductID, ProductName, ProductListPrice, and Profit.
select 
	productid,
    productname,
    productlistprice,
    profit
from product 
order by profit desc
limit 10;


-- 🟡 Intermediate — 

-- Q9 Display each order along with the customer's name and the order date.
-- Display:
-- OrderID
-- OrderDate
-- CustomerID
-- CustomerName
select 
	o.orderid,
    o.orderdate,
    c.customerid,
    c.customername
from customer as c 
join orders as o
on c.customerid = o.customerid;

-- Q10 Find the number of orders placed by each customer.
-- Display:
-- CustomerID
-- CustomerName
-- Total Orders
select 
	c.customerid,
    c.customername,
    count(o.orderid) as total_order
from customer as c
join orders as o
on c.customerid = o.customerid
group by c.customerid, c.customername;

-- Q11 Display every customer along with the number of orders they have placed, including customers who have not placed any orders.
select 
	c.customername,
    count(o.orderid) as num_orders
from customer as c
left join orders as o
on c.customerid = o.customerid
group by c.customerid, c.customername;

-- Q12 Find the total sales generated by each product.
-- Display:
-- ProductID
-- ProductName
-- Total Sales
select 
	p.productid,
    p.productname,
    sum(o.orderitemquantity * o.perunitprice) as total_sales
from product as p
join orderdetails as o
on p.productid = o.productid
group by p.productid, p.productname;

-- Q13 Find the total quantity of products sold in each product category.
-- Display:
-- CategoryName
-- Total Quantity Sold
select 
	p.categoryname,
    count(o.orderitemquantity) as total_quantity
from product as p
join orderdetails as o
on p.productid = o.productid
group by p.categoryname;

-- Q14 Find the product categories whose total sales exceed 50,000.
-- Display:
-- CategoryName
-- Total Sales
select 
	p.categoryname,
    sum(o.orderitemquantity * o.perunitprice) as total_sales
from product as p
join orderdetails as o
on p.productid = o.productid
group by p.categoryname
having total_sales > 50000;

-- Q15 Display every warehouse along with the number of employees assigned to it, including warehouses that have no employees.
-- Display:
-- WarehouseID
-- WarehouseName
-- Employee Count
select 
	w.warehouseid,
    w.warehousename,
    count(e.employeeid) as num_emp
from employee as e
right join warehouse as w
on e.warehouseid = w.warehouseid
group by w.warehouseid, w.warehousename;

-- Q16 Find the total sales generated by each customer.
-- Display:
-- CustomerID
-- CustomerName
-- Total Sales
select 
	c.customerid,
    c.customername,
    sum(o.orderitemquantity * o.perunitprice) as total_sales
from customer as c
left join orders on c.customerid = orders.customerid
left join orderdetails as o on orders.orderid = o.orderid
group by c.customerid, c.customername;


-- 🔴 Advanced — 

-- Q17 Find all products whose list price is greater than the average product list price.
-- Display:
-- ProductID
-- ProductName
-- CategoryName
-- ProductListPrice
select 
	productid,
    productname,
    categoryname,
    productlistprice
from product 
where productlistprice > (select  avg(productlistprice) from product);

-- Q18 Find all employees who work in warehouses located in the region with the highest number of warehouses.
-- Display:
-- EmployeeID
-- EmployeeName
-- WarehouseName
-- RegionID
select 
	e.employeeid,
    e.employeename,
    w.warehousename,
    w.regionid
from employee as e
join warehouse as w
on e.warehouseid = w.warehouseid
where w.regionid = ( select regionid
			from warehouse
            group by regionid
            order by count(regionid) desc 
            limit 1);
 
-- Q19 Find the product categories whose total profit is greater than the average profit of all products.
-- Display:
-- CategoryName
-- Total Profit
select 
	categoryname,
    sum(profit) as total_profit
from product 
group by categoryname
having sum(profit) > ( select avg(profit) from product);
 
-- Q20 Which five products generated the highest total sales revenue? Display the product ID, product name and total sales amount for each.
with highest_sales as (
select 
	p.productid,
    p.productname,
    sum(o.orderitemquantity * o.perunitprice) as total_sales
from product as p
join orderdetails as o
on p.productid = o.productid
group by p.productid, p.productname
order by sum(o.orderitemquantity * o.perunitprice) desc
limit 5 
)
select * from highest_sales;

-- Q21 Find product categories whose total sales are higher than the average sales across all product categories.
-- Display:
-- CategoryName
-- Total Sales
-- Average Category Sales
with category_sales as (
    select
        p.categoryname,
        sum(od.orderitemquantity * od.perunitprice) as total_sales
    from product as p
    join orderdetails as od
	on p.productid = od.productid
    group by p.categoryname
)
select 
	categoryname,
    total_sales,
	(select avg(total_sales) from category_sales) as Average_Category_Sales
from category_sales
where total_sales > (
    select avg(total_sales)
    from category_sales
);

-- Q22 Rank all products based on their profit margin, with the highest profit margin receiving rank 1.
-- Display:
-- ProductID
-- ProductName
-- CategoryName
-- Profit Margin
-- Profit Rank
select 
	productid,
    productname,
    categoryname,
    profitmargin,
    dense_rank() over(order by profitmargin desc) as profit_rank
from (select
        productid,
        productname,
        categoryname,
        (profit / productlistprice) * 100 as profitmargin
    from product
) as p;

-- Q23 Rank products by their list price within each product category with the most expensive product receiving rank 1.
-- Display:
-- CategoryName
-- ProductID
-- ProductName
-- ProductListPrice
-- Category Rank
select
    categoryname,
    productid,
    productname,
    productlistprice,
    dense_rank() over(
        partition by categoryname
        order by productlistprice desc
    ) as category_rank
from product;

-- Q24 Classify products based on their profit margin into three groups:
-- High Margin → 20% or above
-- Medium Margin → 10%–20%
-- Low Margin → below 10%
-- Display:
-- ProductID
-- ProductName
-- CategoryName
-- Profit Margin
-- Profit Category
select
    productid,
    productname,
    categoryname,
    (profit / productlistprice) * 100 as profitmargin,
    case
        when (profit / productlistprice) * 100 >= 20
            then 'High Margin'
        when (profit / productlistprice) * 100 >= 10
            then 'Medium Margin'
        else 'Low Margin'
    end as profit_category
from product;

-- Q25 Create a product performance summary and use it to find the top 10 products based on total sales.
-- Display:
-- ProductID
-- ProductName
-- CategoryName
-- Total Quantity Sold
-- Total Sales
-- Total Profit
create view product_performance as
select
    p.productid,
    p.productname,
    p.categoryname,
    sum(od.orderitemquantity) as total_quantity_sold,
    sum(od.orderitemquantity * od.perunitprice) as total_sales,
    sum(od.orderitemquantity * p.profit) as total_profit
from product as p
join orderdetails od
on p.productid = od.productid
group by
    p.productid,
    p.productname,
    p.categoryname;
    
select
    productid,
    productname,
    categoryname,
    total_quantity_sold,
    total_sales,
    total_profit
from product_performance
order by total_sales desc
limit 10;